# Generated by Django 5.0.2 on 2024-03-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0016_seat_price_seat_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
