# Generated by Django 5.0.2 on 2024-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0018_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plane',
            name='arrival_country',
        ),
        migrations.RemoveField(
            model_name='plane',
            name='departure_country',
        ),
        migrations.AddField(
            model_name='plane',
            name='destination_country',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
