# Generated by Django 5.0.3 on 2024-03-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0022_bookroom_due_amount_bookroom_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritehotel',
            unique_together={('user', 'hotel')},
        ),
    ]
