# Generated by Django 5.0.2 on 2024-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0026_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agency_images/'),
        ),
    ]
