# Generated by Django 5.0.3 on 2024-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbp', '0028_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
